services:
  egcp-service-db:
    image: postgres:latest
    container_name: egcp-service-db
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - /Users/mac/IdeaProjects/EGCPService-db-volumes/EGCPService-db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  egcp-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: egcpservice:latest
    container_name: egcp-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://egcp-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: ${db_username}
      SPRING_DATASOURCE_PASSWORD: ${db_password}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      SPRING_ACTIVEMQ_IN_MEMORY: "false"

      JMS_URL: test.queue

    depends_on:
      egcp-service-db:
        condition: service_healthy
      activemq:
        condition: service_started
    networks:
      - internal

  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - internal

volumes:
  egcp-service-db-volumes:

networks:
  internal:
    driver: bridge