services:
  EGCPService-db:
    image: postgres:latest
    container_name: egcp-service-db
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    volumes:
      - /Users/mac/IdeaProjects/EGCPService-db-volumes/EGCPService-db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  EGCPService:
    build:
      context: .
      dockerfile: Dockerfile
    image: egcpservice:latest
    container_name: egcp-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://EGCPService-db:5432/db
      SPRING_DATASOURCE_USERNAME: ${db_username}
      SPRING_DATASOURCE_PASSWORD: ${db_password}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      EGCPService-db:
        condition: service_healthy
    networks:
      - internal

volumes:
  EGCPService-db-volumes:

networks:
  internal:
    driver: bridge